on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ main ] # Add this trigger to run this workflow on PR's to the main branch
  workflow_dispatch: # to manually run this workflow

env:
  FLUTTER_CHANNEL: 'stable' # 'stable', 'beta', or 'master', default to: 'stable'
  FLUTTER_VERSION: '3.7.12'
  XCODE_VERSION: '14.3'
  PATH_TO_APK: 'build/app/outputs/flutter-apk/app-release.apk'
  ANDROID_PACKAGE_NAME: 'com.base.project'
  PATH_TO_IPA: 'build/ios/ipa/flutter_github_actions_basics.ipa'

jobs:
  # deploy_android:
  #   name: Deploying to Firebase
  #   runs-on: ubuntu-latest
  #   # needs: [build_android]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 12.x

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16

  #     - name: Decode android
  #       run: echo "${{ secrets.KEYSTORE_JKS_PROD }}" | base64 --decode > android/base.jks

  #     - name: Decode android/key.properties
  #       run: echo "${{ secrets.KEY_PROPERTIES_PROD }}" | base64 --decode > android/key.properties

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v1
  #       with:
  #         flutter-version: 3.7.12

  #     - run: flutter pub get

  #     - run: flutter build apk --release

  #     - name: Upload apk artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: release-apk
  #         path: ${{ env.PATH_TO_APK }}

  #     - name: Firebase App Distribution
  #       uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
  #       with:
  #         appId: ${{ secrets.FIREBASE_APP_ID }}
  #         token: ${{ secrets.FIREBASE_TOKEN }}
  #         groups: testers
  #         file: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS App
        run: flutter build ios --release

      - name: Configure Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: configure --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Firebase
        run: firebase appdistribution:distribute ./build/ios/iphoneos/Runner.app.zip --app "${{ secrets.FIREBASE_APP_ID }}" --release-notes "Automatic build deployment" --testers-file "./build/ios/testers.txt"