name: App build
on: push

jobs:
  build_with_signing:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.FS_P12_FILE }}
          P12_PASSWORD: ${{ secrets.FS_P12_PASS }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.FS_PROV_FILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.FS_KEYCHAIN_PASS }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        
      - name: Build app
        run: |
          xcodebuild clean build -workspace MyProject.xcworkspace -scheme MyScheme -destination 'platform=iOS Simulator,name=iPhone 12' CODE_SIGN_STYLE="Manual" CODE_SIGN_IDENTITY="iPhone Distribution" PROVISIONING_PROFILE_SPECIFIER="My Provisioning Profile"
      
      - name: Export archive
        run: |
          xcodebuild archive -workspace MyProject.xcworkspace -scheme MyScheme -destination 'generic/platform=iOS' -archivePath MyProject.xcarchive CODE_SIGN_STYLE="Manual" CODE_SIGN_IDENTITY="iPhone Distribution" PROVISIONING_PROFILE_SPECIFIER="My Provisioning Profile"
      
      - name: Export IPA
        uses: jwalton/xcode-export@v2
        with:
          archive_path: MyProject.xcarchive
          export_options: development
      
      - name: Upload to App Store Connect
        uses: jhaals/transporter-action@v1
        with:
          username: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          password: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
          package_path: MyProject.ipa
        